import * as fs from "node:fs"
import * as path from "node:path"

export type PluralCategory = "zero" | "one" | "two" | "few" | "many" | "other"
export type PluralObject = Partial<Record<PluralCategory, string>>
export type TranslationValue = string | PluralObject
export type TranslationDictionary = Record<string, TranslationValue>

export interface ParsedParam {
    name: string
    type: string
}

export interface ParsedTemplate {
    params: ParsedParam[]
    template: string
}

/** plural object type guard */
function isPluralObject(value: unknown): value is PluralObject {
    return (
        typeof value === "object" &&
        value !== null &&
        !Array.isArray(value) &&
        Object.keys(value).some((key) => ["zero", "one", "two", "few", "many", "other"].includes(key))
    )
}

// 3. template parser ({name:string}, {count:number})
function parseTemplate(text: string): ParsedTemplate {
    const matches = [...text.matchAll(/\{(\w+)(?::(\w+))?\}/g)]
    const paramMap = new Map<string, string>()

    for (const match of matches) {
        const paramName = match[1]
        const explicitType = match[2]

        if (paramName && !paramMap.has(paramName)) {
            // if name is count/amount/days we make it number, else we set it as string
            const defaultType = ["count", "amount", "days", "num", "total"].includes(paramName) ? "number" : "string"

            paramMap.set(paramName, explicitType ?? defaultType)
        }
    }

    const params: ParsedParam[] = Array.from(paramMap.entries()).map(([name, type]) => ({
        name,
        type
    }))

    // replace {param:type} to ${p.param} as template literal
    const template = text.replace(/\{(\w+)(?::\w+)?\}/g, "${p.$1}")

    return { params, template }
}

// language function generator
function generateFunctions(lang: string, dict: TranslationDictionary): string {
    const lines: string[] = []

    for (const [key, value] of Object.entries(dict)) {
        if (key.startsWith("@")) continue
        if (isPluralObject(value)) {
            const branches = Object.entries(value)
                .map(([k, text]) => {
                    const { template } = parseTemplate(text)
                    return `    ${k}: \`${template}\``
                })
                .join(",\n")

            lines.push(`  ${key}: (p: { count: number }) => plural('${lang}', p.count, {\n${branches}\n  })`)
            continue
        }

        if (typeof value === "string") {
            const { params, template } = parseTemplate(value)

            if (params.length === 0) {
                lines.push(`  ${key}: () => ${JSON.stringify(value)}`)
            } else {
                const typeSignature = params.map((p) => `${p.name}: ${p.type}`).join("; ")
                lines.push(`  ${key}: (p: { ${typeSignature} }) => \`${template}\``)
            }
        }
    }

    return lines.join(",\n")
}

// main compiler function
export function compileI18n(
    localesDir = "./i18n/locales",
    outputFile = "./src/generated/i18n.ts",
    baseLocale = "en"
): void {
    const resolvedLocalesDir = path.resolve(localesDir)
    const resolvedOutputFile = path.resolve(outputFile)

    if (!fs.existsSync(resolvedLocalesDir)) {
        throw new Error(`locale dir not found: ${resolvedLocalesDir}`)
    }

    // read all jsons
    const files = fs.readdirSync(resolvedLocalesDir).filter((file) => file.endsWith(".json"))
    const locales = files.map((file) => path.basename(file, ".json"))

    if (!locales.includes(baseLocale)) {
        throw new Error(`base locale "${baseLocale}.json" does not exist in ${localesDir}`)
    }

    const dictionaries: Record<string, TranslationDictionary> = {}

    for (const locale of locales) {
        const filePath = path.join(resolvedLocalesDir, `${locale}.json`)
        const content = fs.readFileSync(filePath, "utf-8")
        dictionaries[locale] = JSON.parse(content) as TranslationDictionary
    }

    // creating plural rules for all langs
    const pluralRulesEntries = locales.map((locale) => `  ${locale}: new Intl.PluralRules('${locale}')`).join(",\n")

    // generating dicts (with ...en fallback)
    const baseDictCode = `export const ${baseLocale} = {\n${generateFunctions(
        baseLocale,
        dictionaries[baseLocale]!
    )}\n} as const;\n\nexport type Dict = typeof ${baseLocale};`

    const otherLocalesCode = locales
        .filter((l) => l !== baseLocale)
        .map((locale) => {
            return `export const ${locale}: Dict = {\n  ...${baseLocale},\n${generateFunctions(
                locale,
                dictionaries[locale]!
            )}\n};`
        })
        .join("\n\n")

    const dictMapEntries = locales.map((l) => `  ${l}`).join(",\n")

    // generated ts file
    const generatedCode = `// this file was generated by i18n/build.ts, do not edit manually


const prs: Record<string, Intl.PluralRules> = {
${pluralRulesEntries}
};


function plural(lang: string, count: number, forms: Partial<Record<Intl.LDMLPluralRule, string>>): string {
  const rule = prs[lang]?.select(count) ?? 'other';
  return forms[rule] ?? forms.other ?? '';
}


${baseDictCode}


${otherLocalesCode}


export const dictionaries = {
${dictMapEntries}
} as const;


export type SupportedLocale = keyof typeof dictionaries;


export function getT(locale?: string): Dict {
  if (locale && locale in dictionaries) {
    return dictionaries[locale as SupportedLocale];
  }
  return dictionaries.${baseLocale};
}
`

    // creating folder
    fs.mkdirSync(path.dirname(resolvedOutputFile), { recursive: true })
    fs.writeFileSync(resolvedOutputFile, generatedCode, "utf-8")

    console.log(`locales successfully compiled to: ${outputFile}`)
    console.log(`found locales: ${locales.join(", ")} (base: ${baseLocale})`)
}

compileI18n()
