// Generated by `seedcord codegen`. Do not edit by hand.
// Run `seedcord codegen` after changing your commands, plugins, or emoji config.

// prettier-ignore
declare module '@seedcord/gateway' {
    interface SlashRegistry {
        cat: { options: {}; cache: 'cached' };
        credits: { options: {}; cache: 'cached' };
        ping: { options: { detailed: { kind: 'boolean'; required: false } }; cache: 'cached' };
        removechannel: { options: {}; cache: 'cached' };
        setchannel: { options: { channel: { kind: 'channel'; required: true; channelTypes: [2] }; category: { kind: 'channel'; required: false; channelTypes: [4] }; template: { kind: 'string'; required: false }; language: { kind: 'string'; required: false; choices: ['en', 'be', 'ru'] } }; cache: 'cached' };
        settings: { options: {}; cache: 'cached' };
        setup: { options: {}; cache: 'cached' };
    }
    interface UserContextMenuRegistry {

    }
    interface MessageContextMenuRegistry {

    }
    interface EmojiMap {
        bitrate: 'guild';
        booster: 'guild';
        delete: 'guild';
        edit: 'guild';
        kick: 'guild';
        lock: 'guild';
        members: 'guild';
        mod: 'guild';
        next: 'guild';
        pause: 'guild';
        play: 'guild';
        requests: 'guild';
        setup: 'guild';
        stop: 'guild';
        sync: 'guild';
        unlock: 'guild';
        voiceLimited: 'guild';
    }
}

export {};
