// Generated by `seedcord codegen`. Do not edit by hand.
// Run `seedcord codegen` after changing your commands, plugins, or emoji config.

// prettier-ignore
declare module '@seedcord/gateway' {
    interface SlashOptionRegistry {
        ping: { detailed: { kind: 'boolean'; required: false } };
        setchannel: { channel: { kind: 'channel'; required: true; channelTypes: [2] }; category: { kind: 'channel'; required: true; channelTypes: [4] } };
    }
    interface UserContextMenuRegistry {

    }
    interface MessageContextMenuRegistry {

    }
    interface EmojiMap {
        bitrate: 'guild';
        booster: 'guild';
        delete: 'guild';
        edit: 'guild';
        kick: 'guild';
        lock: 'guild';
        members: 'guild';
        mod: 'guild';
        play: 'guild';
        setup: 'guild';
        unlock: 'guild';
        voiceLimited: 'guild';
    }
}

export {};
